### ISSUE TITLE
Errors on the getting started guide

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst-docs#10]
Hi,

I just installed catalyst following the getting started guide on the site:

STEP 1:
```
$ virtualenv catalyst-venv
$ source ./catalyst-venv/bin/activate
$ pip install enigma-catalyst
$ pip install matplotlib
```

During STEP 3:

After:
```
$ catalyst ingest
```

I get:
```
Error: No bundle registered with the name None
```

After:
```
$ catalyst run -f buy_and_hodl.py --start 2015-3-2 --end 2017-6-28 --capital-base 100000 -o bah.pickle
```

I get:
```
[2017-10-23 22:04:43.953848] INFO: run_algo: running algo in backtest mode
[2017-10-23 22:04:45.457986] INFO: exchange_bundle: pricing data for [u'btc_usdt'] not found in range 2015-03-01 00:00:00+00:00 to 2017-06-27 00:00:00+00:00, updating the bundles.
    [====================================]  Fetching poloniex daily candles: :  100%             
[2017-10-23 22:04:48.153406] INFO: Loader: Cache at /home/av/.catalyst/data/treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-06-27 00:00:00+00:00.
[2017-10-23 22:04:48.153574] INFO: Loader: Downloading treasury data for 'btc_usdt'.
[2017-10-23 22:04:52.258527] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Error traceback: /home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/exchange/exchange.py (line 175)
SymbolNotFoundOnExchange:  Symbol USDT_BTC not found on exchange Poloniex. Choose from: ['rep_usdt', 'gno_btc', 'xvc_btc', 'pink_btc', 'sys_btc', 'emc2_btc', 'rads_btc', 'note_btc', 'maid_btc', 'bch_btc', 'gnt_btc', 'bcn_btc', 'rep_btc', 'bcy_btc', 'cvc_btc', 'nxt_xmr', 'zec_usdt', 'fct_btc', 'gas_btc', 'pot_btc', 'eth_usdt', 'btc_usdt', 'lbc_btc', 'dcr_btc', 'etc_usdt', 'omg_eth', 'amp_btc', 'xpm_btc', 'nxt_btc', 'vtc_btc', 'steem_eth', 'blk_xmr', 'pasc_btc', 'zec_xmr', 'grc_btc', 'nxc_btc', 'btcd_btc', 'ltc_btc', 'dash_btc', 'naut_btc', 'zec_eth', 'zec_btc', 'burst_btc', 'zrx_eth', 'bela_btc', 'steem_btc', 'etc_btc', 'eth_btc', 'huc_btc', 'strat_btc', 'lsk_btc', 'exp_btc', 'clam_btc', 'rep_eth', 'dash_xmr', 'cvc_eth', 'bch_usdt', 'zrx_btc', 'dash_usdt', 'blk_btc', 'xrp_btc', 'nxt_usdt', 'neos_btc', 'omg_btc', 'bts_btc', 'doge_btc', 'gnt_eth', 'sbd_btc', 'gno_eth', 'xcp_btc', 'ltc_usdt', 'btm_btc', 'xmr_usdt', 'lsk_eth', 'omni_btc', 'nav_btc', 'fldc_btc', 'ppc_btc', 'xbc_btc', 'dgb_btc', 'sc_btc', 'btcd_xmr', 'vrc_btc', 'ric_btc', 'str_btc', 'maid_xmr', 'xmr_btc', 'sjcx_btc', 'via_btc', 'xem_btc', 'nmc_btc', 'etc_eth', 'ltc_xmr', 'ardr_btc', 'gas_eth', 'flo_btc', 'xrp_usdt', 'game_btc', 'bch_eth', 'bcn_xmr', 'str_usdt']
```

I thought I needed to change `USDT_BTC` for `btc_usdt`, and after I did it, I got:
```
[2017-10-23 22:06:21.534860] INFO: run_algo: running algo in backtest mode
[2017-10-23 22:06:22.402738] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "/home/av/repos/crypto/catalyst/.env/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/__main__.py", line 101, in _
    return f(*args, **kwargs)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/__main__.py", line 275, in run
    live_graph=False
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/utils/run_algo.py", line 336, in _run
    overwrite_sim_params=False,
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/algorithm.py", line 725, in run
    for perf in self.get_generator():
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/av/repos/crypto/catalyst/.env/lib/python2.7/site-packages/catalyst/algorithm.py", line 474, in handle_data
    self._handle_data(self, data)
  File "buy_and_hodl.py", line 59, in handle_data
    price = data[context.asset].price
  File "catalyst/_protocol.pyx", line 817, in catalyst._protocol.BarData.__getitem__
  File "catalyst/_protocol.pyx", line 211, in catalyst._protocol.BarData._get_equity_price_view
AttributeError: 'NoneType' object has no attribute 'retrieve_asset'
```

Am I doing something wrong?

Thanks.

**Comment by chaltik** [comment]
Just installed catalyst, and was able reproduce all of the issues above (code not working as expected, and unable to register for slack channel) one for one.

**Comment by jsuagee** [comment]
Hi, I am not a developer on this project but I think that buy_and_hodl.py has been modified as of 5 days ago to fix this. The change was to replace the accessor method used on the data object in line 59.
`price = data[context.asset].price` was replaced with `price = data.current(context.asset, 'price')` and similarly in several other places.

At least that is what I suspect. I did not try out this particular example myself but ran into a similar issue modifying an [example script](https://github.com/enigmampc/catalyst-docs/wiki/Script-to-extract-market-data-(price-and-volume)-from-one-cryptocurrency) to get daily price/volume data.

So you might want to clone the github repository itself instead of installing it via pip. In case you do not know: In [this page](https://github.com/enigmampc/catalyst-docs/wiki/Update-Poloniex-data-bundle-for-use-with-Catalyst) of the docs it is described how to install a local copy of catalyst. You simply
`pip install catalyst/` from within the directory containing your clone of the git repo (note the trailing slash).

Hope this helps!

**Comment by vonpupp** [comment]
Thank you very much @jsuagee,

I tried following the steps described on the link you provided (using branch `0.3`) and I had the same error:
```
Error: No bundle registered with the name None
```

Best regards!

**Comment by lacabra** [comment]
@vonpupp please upgrade to the latest version 0.3.3 using `pip install --upgrade enigma-catalyst` and refer to the documentation available at https://enigmampc.github.io/catalyst. The use of `catalyst ingest` is deprecated in favor of `catalyst ingest-exchange {exchange_name}` where {exchange_name} is either bittrex, bitfinex or poloniex. And the code examples you mention also get updated as the code evolves, so make sure you are always using the latest version of the examples from our repository: https://github.com/enigmampc/catalyst/tree/master/catalyst/examples

**Comment by piggehz** [comment]
Thanks @lacabra - the correct command now seems to be `catalyst ingest-exchange -x {exchange_name}`
